name: Clang Format Checker
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - staged
    paths-ignore:
      - 'docs/**'
      - ".github/**"
      - "howto/**"
  pull_request:
    branches:
      - dev
      - staged
    paths-ignore:
      - 'docs/**'
      - ".github/**"
      - "howto/**"
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v1.0.1
        with:
          sources: "**/*.c,**/*.h,**/*.cc,**/*.hh,**/*.cpp,**/*.hpp"
